#!/usr/bin/env python3

from reports import generate_pdf 
import os
from datetime import date
from emails import generate_email, send_email



def format_date():
    x = date.today()
    return "{} {}, {}".format(x.strftime("%B"), x.strftime("%d"), x.strftime("%Y"))

def process_fruits(dir_path):
    
    dirs = os.listdir( dir_path )

    abs_path =  os.path.abspath(dir_path)
    
    
    fruits = []
    
    
    for file in dirs:
        print(file)
        file_path = os.path.splitext(file)
            #print(file_path)

        if file_path[1] == ".txt":
            print("Found text file")
            print("\t" + file)
            print("---------------")

            abs_file_path = abs_path+"/"+file
            print(abs_file_path)
            with open(abs_file_path, "r") as f:
                p = {}


                txt = f.read()

                txt_arr = txt.split( "\n" )

                p["name"] = txt_arr[0]
                p["weight"] = txt_arr[1]
                fruits.append(p)

    print(fruits)
    return fruits
    
    
if __name__ == "__main__":
    title = "Processed Update on " + str(format_date())
    fruits = process_fruits("supplier-data/descriptions/")
    
    
    #/tmp/processed.pdf
    generate_pdf("/tmp/processed.pdf", title, fruits)
    
    
    sender = "automation@example.com"
    # use from connection tab
    receiver = "{}@example.com".format(os.environ.get('USER'))
    subject = "Upload Completed - Online Fruit Store"
    body = "All fruits are uploaded to our website successfully. A detailed list is attached to this email."
    attachment = "/tmp/processed.pdf"
    
    message = generate_email(sender, receiver, subject, body, attachment)
    print(message)
    # send_email
    send_email(message)

